### ISSUE TITLE
Figure out different hosting for all the image files

### ISSUE THREAD

**Issue by LindseyB** [LindseyB/GIFs#40]
:[ image files are too big I need a different host for them and maybe a whole non-jekyll site probably

```[tasklist]
### Tasks
- [ ] Convert all the GIFs to WEBM for smaller size
- [ ] Upload all WEBMs to s3 
- [ ] Create a yaml file mapping of the gif name/path to s3 path
- [ ] Create a crude search from the filenames
- [ ] Allow videos to be downloaded as webm or gif (then we should just store both tbh) 
```
